<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="himanshu507-lambdatests-mz510735rot" failures="0" tests="10" name="lambdatest.Tests.TestScenario3" time="376.256" errors="2" timestamp="2023-02-23T18:13:53 UTC" skipped="4">
  <testcase classname="lambdatest.Tests.TestScenario3" name="checkFieldsMsg" time="2.455"/>
  <system-out/>
  <testcase classname="lambdatest.Tests.TestScenario3" name="SubmitData" time="0.001">
    <skipped/>
  </testcase> <!-- SubmitData -->
  <system-out/>
  <testcase classname="lambdatest.Tests.TestScenario3" name="checkFieldsMsg" time="2.354"/>
  <system-out/>
  <testcase classname="lambdatest.Tests.TestScenario3" name="setup" time="180.009">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at lambdatest.TestComponents.BaseTest.setup(BaseTest.java:98)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
]]>
    </error>
  </testcase> <!-- setup -->
  <system-out/>
  <testcase classname="lambdatest.Tests.TestScenario3" name="SubmitData" time="4.922"/>
  <system-out/>
  <testcase classname="lambdatest.Tests.TestScenario3" name="SubmitData" time="6.417"/>
  <system-out/>
  <testcase classname="lambdatest.Tests.TestScenario3" name="SubmitData" time="0.000">
    <skipped/>
  </testcase> <!-- SubmitData -->
  <system-out/>
  <testcase classname="lambdatest.Tests.TestScenario3" name="setup" time="180.098">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at lambdatest.TestComponents.BaseTest.setup(BaseTest.java:98)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
]]>
    </error>
  </testcase> <!-- setup -->
  <system-out/>
  <testcase classname="lambdatest.Tests.TestScenario3" name="checkFieldsMsg" time="0.000">
    <skipped/>
  </testcase> <!-- checkFieldsMsg -->
  <system-out/>
  <testcase classname="lambdatest.Tests.TestScenario3" name="checkFieldsMsg" time="0.000">
    <skipped/>
  </testcase> <!-- checkFieldsMsg -->
  <system-out/>
</testsuite> <!-- lambdatest.Tests.TestScenario3 -->
